# Generated by Django 4.0.4 on 2022-05-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_productos_cantidad_stock_productos_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
