# Generated by Django 4.0.4 on 2022-05-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('documento', models.BigIntegerField(default=0)),
                ('telefono', models.BigIntegerField(default=0)),
                ('correo', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('producto', models.CharField(max_length=255)),
                ('costo', models.BigIntegerField(default=0)),
            ],
        ),
    ]
